### ISSUE TITLE
Training/Evaluating on Open Images V6

### ISSUE THREAD

**Issue by coldmanck** [Scarecrow0/BGNN-SGG#3]
Thank you for the awesome work. 

I would like to work on SGG with OI v6, and it seems that your work is, to the best of my knowledge, the first to evaluate on OI v6. I know it takes time to clear codebases before releasing the whole codebase, thus I am wondering is it possible to release the data loader/loading functions first so that people can evaluate SGG models under the same setting?

Moreover, I've a couple of questions and I hope to get you help to clarify:
- I found the visual relationships annotations in OIv6 do not seem to include bounding boxes but only union boxes. In this case, how did you obtain ground truth subject/object boxes?
- It seems only 21 out of 30 predicates (excluding `is` predicate) shows up in the current OIv6 testing split. How do you calculate mean recall in this case (e.g. simply neglecting them?)

Thank you!

**Comment by Scarecrow0** [comment]
- I download the initial dataset annotation(oidv6-train/test/validation-annotations-vrd.csv) from [offical website]( https://storage.googleapis.com/openimages/web/download.html) 
.  As you can see, the annotation included both subject and object entities boxes and categories.
![image](https://user-images.githubusercontent.com/26022232/121305246-f5d5af80-c92f-11eb-8a29-fe2402c1f94b.png)
- I ignore the "is" categories since it is the unitary attribute. There do have some relationships that don't occur in the test set. I follow the [previous implementation](https://github.com/NVIDIA/ContrastiveLosses4VRD/blob/master/lib/datasets_rel/task_evaluation_sg.py) that simply set the recall/AP of those relationships as 0.

![image](https://user-images.githubusercontent.com/26022232/121306280-3681f880-c931-11eb-9579-cede53d09b63.png)

- Here is the [processed dataset (38GB)](https://shanghaitecheducn-my.sharepoint.com/:u:/g/personal/lirj2_shanghaitech_edu_cn/EXdZWvR_vrpNmQVvubG7vhABbdmeKKzX6PJFlIdrCS80vw?e=uQREX3) and [processing .ipynb](https://shanghaitecheducn-my.sharepoint.com/:u:/g/personal/lirj2_shanghaitech_edu_cn/EebESIOrpR5NrOYgQXU5PREBPR9EAxcVmgzsTDiWA1BQ8w?e=46iDwn). (remove the images without relationship annotation and transform the entities annotation into independent form with relationships.)

**Comment by coldmanck** [comment]
Thank you for the clarification. That really helps!

**Comment by yrcong** [comment]
Great!
